# -*- coding: utf-8 -*-
"""proyecto_S5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnZeWytwiQt05Z5FltSFnWD8TMIL5Lm8

# ¿Cuál es la mejor tarifa?

Trabajas como analista para el operador de telecomunicaciones Megaline. La empresa ofrece a sus clientes dos tarifas de prepago, Surf y Ultimate. El departamento comercial quiere saber cuál de las tarifas genera más ingresos para poder ajustar el presupuesto de publicidad.

Vas a realizar un análisis preliminar de las tarifas basado en una selección de clientes relativamente pequeña. Tendrás los datos de 500 clientes de Megaline: quiénes son los clientes, de dónde son, qué tarifa usan, así como la cantidad de llamadas que hicieron y los mensajes de texto que enviaron en 2018. Tu trabajo es analizar el comportamiento de los clientes y determinar qué tarifa de prepago genera más ingresos.

El propósito de este proyecto es evaluar y comparar los patrones de consumo y los ingresos generados por los diferentes planes tarifarios ofrecidos por la compañía, así como analizar si existen diferencias significativas entre los usuarios según su localidad. Para ello, se realizará un estudio detallado del comportamiento mensual de uso —minutos de llamada, mensajes y datos móviles— y se examinará cómo estos consumos se traducen en cargos mensuales para los usuarios.

El análisis incluirá varias etapas:

Exploración y visualización del consumo, utilizando histogramas y boxplots para identificar patrones generales y posibles valores atípicos.

Cálculo de estadísticas descriptivas, como medias, medianas y rangos intercuartílicos, con el fin de caracterizar el comportamiento típico de los usuarios.

Comparación de ingresos entre planes y localidades, determinando si existen diferencias significativas mediante pruebas de hipótesis.

Selección de pruebas estadísticas adecuadas, tomando en cuenta la distribución de los datos y la igualdad o desigualdad de varianzas entre los grupos.

Interpretación de resultados, enfocada en comprender qué factores influyen más en los ingresos y qué segmentos de usuarios generan mayor variabilidad o estabilidad en los pagos.

## Inicialización
"""

# Cargar todas las librerías

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from scipy import stats as st

"""## Cargar datos"""

# Carga los archivos de datos en diferentes DataFrames
calls= pd.read_csv('https://code.s3.yandex.net/datasets/megaline_calls.csv')
internet= pd.read_csv('https://code.s3.yandex.net/datasets/megaline_internet.csv')
messages = pd.read_csv('https://code.s3.yandex.net/datasets/megaline_messages.csv')
plans = pd.read_csv('https://code.s3.yandex.net/datasets/megaline_plans.csv')
users = pd.read_csv('https://code.s3.yandex.net/datasets/megaline_users.csv')

"""## Preparar los datos

## Tarifas
"""

# Imprime la información general/resumida sobre el DataFrame de las tarifas

plans.info()

# Imprime una muestra de los datos para las tarifas

display(plans)

plans['gb_per_month_included']= (plans['mb_per_month_included'] / 1024).astype('int')
display(plans)

"""El data set de tarifas no tiene inconsistencias ni cosas que corregir. sólo hace falta convertir mb a gb de datos móbiles. Para esto se creó una nueva columna donde se convierte los mb que ofrece cada plan a gb.

## Corregir datos

## Enriquecer los datos
"""



"""## Usuarios/as"""

# Imprime la información general/resumida sobre el DataFrame de usuarios
users.info()

# Imprime una muestra de datos para usuarios

display(users.sample(10))

"""En el dataset de usuarios sólo falta convertir el tipo de dato de las columnas de fecha (reg_date y churn_date) a formato datetime. Esto puede hacerse con el método de Pandas pd.to_datetime(), especificando el formato de fecha '%Y-%m-%d'.

En la columna churn_date, la mayoría de los valores son NA debido a que los usuarios aún no se habían retirado al momento de la extracción de los datos.

También se extrajo el mes de la fecha para los análisis posteriores.

### Corregir los datos
"""

users['reg_date'] = pd.to_datetime(users['reg_date'], format = '%Y-%m-%d')
users['churn_date'] = pd.to_datetime(users['churn_date'], format = '%Y-%m-%d')

users.info()

"""### Enriquecer los datos"""

users['reg_month'] = users['reg_date'].dt.month

users['churn_month'] = users['churn_date'].dt.month

"""## Llamadas"""

# Imprime la información general/resumida sobre el DataFrame de las llamadas
calls.info()

# Imprime una muestra de datos para las llamadas
display(calls.sample(10))

"""El tipo de dato de la columna call_date es de tipo object, por lo que es necesario convertirlo a datetime para poder trabajar correctamente con fechas.

También se extrajo el mes de la fecha para los análisis posteriores.

### Corregir los datos
"""

calls['call_date'] = pd.to_datetime(calls['call_date'], format = '%Y-%m-%d')

"""### Enriquecer los datos"""

calls['month'] = calls['call_date'].dt.month

"""## Mensajes"""

messages.info()# Imprime la información general/resumida sobre el DataFrame de los mensajes

# Imprime una muestra de datos para los mensajes
display(messages.sample(10))

"""El tipo de dato de la columna message_date es de tipo object, por lo que es necesario convertirlo a datetime para poder trabajar correctamente con fechas.

También se extrajo el mes de la fecha para los análisis posteriores.

### Corregir los datos
"""

messages['message_date'] = pd.to_datetime(messages['message_date'], format = '%Y-%m-%d')

"""### Enriquecer los datos"""

messages['month'] = messages['message_date'].dt.month

"""## Internet"""

internet.info()# Imprime la información general/resumida sobre el DataFrame de internet

display(internet.sample(10))# Imprime una muestra de datos para el tráfico de interndisplay(internet.sample(10))

"""El tipo de dato de la columna session_date es de tipo object, por lo que es necesario convertirlo a datetime para poder trabajar correctamente con fechas.

También se extrajo el mes de la fecha para los análisis posteriores.

### Corregir los datos
"""

internet['session_date'] = pd.to_datetime(internet['session_date'], format = '%Y-%m-%d')

"""### Enriquecer los datos"""

internet['month'] = internet['session_date'].dt.month

"""## Estudiar las condiciones de las tarifas"""

# Imprime las condiciones de la tarifa y asegúrate de que te quedan claras

display(plans)

"""## Agregar datos por usuario


"""

# Calcula el número de llamadas hechas por cada usuario al mes. Guarda el resultado.

calls_per_month = calls.groupby(by= ['user_id','month'])['duration'].count().rename('num_calls')

# Calcula la cantidad de minutos usados por cada usuario al mes. Guarda el resultado.

calls_minutes_per_month = calls.groupby(by= ['user_id','month'])['duration'].sum().rename('call_duration')

# Calcula el número de mensajes enviados por cada usuario al mes. Guarda el resultado.
messages_per_month = messages.groupby(by = ['user_id','month'])['id'].count().rename('num_messages')

# Calcula el volumen del tráfico de Internet usado por cada usuario al mes. Guarda el resultado.

internet_use_per_month = internet.groupby(by = ['user_id','month'])['mb_used'].sum()

# Fusiona los datos de llamadas, minutos, mensajes e Internet con base en user_id y month
consumo_mensual = pd.concat([calls_per_month, calls_minutes_per_month, messages_per_month, internet_use_per_month], axis = 1)

# Añade la información de la tarifa

consumo_mensual.head(20)

planes = users.set_index('user_id')['plan']
consumo_mensual = consumo_mensual.reset_index()
consumo_mensual['plan'] = consumo_mensual['user_id'].map(planes)
consumo_mensual = consumo_mensual.set_index(['user_id', 'month'])

consumo_mensual.fillna(0, inplace = True)
consumo_mensual['num_calls'] = consumo_mensual['num_calls'].astype(int)
consumo_mensual['num_messages'] = consumo_mensual['num_messages'].astype(int)
display(consumo_mensual.head(20))

"""## Estudia el comportamiento de usuario

### Llamadas
"""

# Compara la duración promedio de llamadas por cada plan y por cada mes. Traza un gráfico de barras para visualizarla.

average_call = consumo_mensual.groupby(by = 'plan')['call_duration'].mean()
print(f'El tiempo promedio de llamada es: \n{average_call}')

# Compara el número de minutos mensuales que necesitan los usuarios de cada plan. Traza un histograma.

plt.figure(figsize=(15,5))
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'surf']['call_duration'], bins=40, alpha=0.6, label='Surf')
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'ultimate']['call_duration'], bins=40, alpha=0.6, label='Ultimate')
plt.title('Comparación de la duración de llamadas entre usuarios con distintos planes')
plt.xlabel('Minutos')
plt.ylabel('Frecuencia')
plt.legend()
plt.show()

# Calcula la media y la varianza de la duración mensual de llamadas.

print(f'Duración promedio de llamadas: {consumo_mensual['call_duration'].mean()} minutos')

print(f'Desviación de la duración de llamadas: {consumo_mensual['call_duration'].var()} minutos')

# Traza un diagrama de caja para visualizar la distribución de la duración mensual de llamadas
plt.figure(figsize=(3,6))
caja = sns.boxplot(data=consumo_mensual, y='call_duration',  palette= ['#3498db'])
caja.set( ylabel='Minutos', title='Distribución de duración de llamadas mensuales')
plt.show()

plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='plan', y='call_duration', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='Plan', ylabel='Minutos', title='Distribución de duración de llamadas mensuales por plan')

plt.show()

"""En el histograma se observa que existe una mayor cantidad de consumidores con el plan surf. A pesar de esta diferencia en el tamaño de la muestra, los patrones de consumo de minutos en ambos planes son muy similares: las distribuciones tienen formas parecidas y las medidas de tendencia central son prácticamente iguales.

Esto se confirma en el boxplot, donde puede apreciarse que la mediana de la duración mensual de llamadas es casi idéntica para ambos planes, situándose alrededor de los 400 minutos. Asimismo, el rango intercuartílico es muy parecido en los dos grupos, lo que indica un nivel similar de variabilidad en el consumo mensual.

Un aspecto adicional es que una proporción considerable de usuarios del plan surf (ligeramente más del 25%) supera el límite de 500 minutos incluidos sin recargos, lo que implica que este segmento genera ingresos adicionales mediante pagos por exceso de uso. En cambio, los usuarios del plan ultimate no exceden el límite de 3000 minutos sin recargos, por lo que el número de clientes que generan ingresos extra es nulo.

### Mensajes
"""

# Comprara el número de mensajes que tienden a enviar cada mes los usuarios de cada plan
plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='plan', y='num_messages', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='Plan', ylabel='Número de mensajes', title='Distribución cantidad de mensajes mensuales por plan')

plt.show()

# Compara la cantidad de tráfico de Internet consumido por usuarios por plan

plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='plan', y='mb_used', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='Plan', ylabel='mb de internet consumidos', title='Distribución cantidad de mb de internet usados mensualmente por plan')

plt.show()

"""A simple vista, parece que el 50% de los usuarios del plan ultimate envían más mensajes que el 50% de los usuarios del plan surf, lo cual concuerda con la posición más alta de la mediana en el boxplot de ultimate.

Esto podría deberse a que el plan ultimate incluye una mayor cantidad de mensajes sin recargo, lo que permitiría a los usuarios enviar más mensajes sin preocuparse por costos adicionales.

Por otra parte, aunque la mayoría de los usuarios surf envía menos mensajes, la gráfica muestra que existe un grupo pequeño (menos del 25%) que excede claramente el límite de mensajes incluidos en el plan. Estos consumidores podrían estar generando ingresos adicionales por recargos de consumo.

### Internet
"""

plt.figure(figsize=(15,5))
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'surf']['mb_used'], bins=40, alpha=0.6, label='Surf')
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'ultimate']['mb_used'], bins=40, alpha=0.6, label='Ultimate')
plt.title('Comparación de mb de internet usados entre usuarios con distintos planes')
plt.xlabel('Mb')
plt.ylabel('Frecuencia')
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='plan', y='mb_used', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='Plan', ylabel='mb de internet consumidos', title='Distribución cantidad de mb de internet usados mensualmente por plan')

plt.show()

"""Al igual que en el consumo de minutos de llamada, los patrones de uso de datos móviles entre los dos planes son muy similares: las distribuciones tienen formas parecidas, las medianas están prácticamente al mismo nivel y el rango intercuartílico es casi idéntico.

Sin embargo, un hallazgo importante es que una proporción considerable de usuarios del plan surf supera el límite de 15 GB incluidos sin recargos, lo que indica que este plan genera ingresos adicionales debido al exceso de consumo de datos.

Por el contrario, aunque el plan ultimate tiene un límite mayor de 30 GB, la mayoría de sus usuarios permanece dentro de este rango y solo unos pocos lo exceden. Esto sugiere que el plan ultimate tiene muchos menos usuarios que generan cargos adicionales por datos en comparación con surf, no obstante se necesita calcular el ingreso de recargos considerando las tarifas de cada plan para averiguar cuál genera más ingresos.

## Ingreso
"""

#calcular el sobreconsumo y sobrecargos.

def calcular_sobreconsumo(df, planes, columna_df, columna_planes, tarifa_column, columna_excedente, columna_sobrecargo):

    included_surf, tarifa_surf = planes.loc[planes['plan_name'] == 'surf', [columna_planes, tarifa_column]].iloc[0]
    df.loc[df['plan']== 'surf', columna_excedente] = ((included_surf - df[columna_df]) * (-1))

    included_ultimate, tarifa_ultimate = planes.loc[planes['plan_name'] == 'ultimate', [columna_planes, tarifa_column]].iloc[0]
    df.loc[df['plan']== 'ultimate', columna_excedente] = ((included_ultimate - df[columna_df]) * (- 1))

    df[columna_excedente].where( df[columna_excedente] > 0, 0,inplace=True)

    df.loc[df['plan']== 'surf', columna_sobrecargo] = (df[columna_excedente] * tarifa_surf)
    df.loc[df['plan']== 'ultimate', columna_sobrecargo] = (df[columna_excedente] * tarifa_ultimate)


    return df[[columna_excedente, columna_sobrecargo]]

# Calculamos los gb consumnidos y los redondeamos hacia arriba.
consumo_mensual['gb_used'] = np.where((consumo_mensual['mb_used'] / 1024) % 1 > 0 , ((consumo_mensual['mb_used'] / 1024).astype(int) + 1), (consumo_mensual['mb_used'] / 1024).astype(int))

consumo_mensual[['excedente_min', 'sobrecargo_min']]= calcular_sobreconsumo(consumo_mensual, plans, 'call_duration', 'minutes_included','usd_per_minute', 'excedente_min', 'sobrecargo_min')

consumo_mensual[['excedente_men', 'sobrecargo_men']]= calcular_sobreconsumo(consumo_mensual, plans, 'num_messages', 'messages_included','usd_per_message', 'excedente_men', 'sobrecargo_men')

consumo_mensual[['excedente_gb', 'sobrecargo_gb']]= calcular_sobreconsumo(consumo_mensual, plans, 'gb_used', 'gb_per_month_included','usd_per_gb', 'excedente_gb', 'sobrecargo_gb')

consumo_mensual['total_sobrecargos'] = consumo_mensual['sobrecargo_min'] + consumo_mensual['sobrecargo_men'] + consumo_mensual['sobrecargo_gb']


costo_surf = plans.loc[plans['plan_name']== 'surf', 'usd_monthly_pay'].iloc[0]
costo_ultimate = plans.loc[plans['plan_name']== 'ultimate', 'usd_monthly_pay'].iloc[0]
consumo_mensual['total_mensual'] = np.where(consumo_mensual['plan'] == 'surf', consumo_mensual['total_sobrecargos'] + costo_surf , consumo_mensual['total_sobrecargos'] + costo_ultimate)

display(consumo_mensual[['plan','sobrecargo_min', 'sobrecargo_men', 'sobrecargo_gb', 'total_sobrecargos', 'total_mensual']].head(20))

print('Usuarios con plan surf:')
display(consumo_mensual.loc[consumo_mensual['plan'] == 'surf', 'total_mensual'].describe())
print("=============================================================================================================")
print('Usuarios con plan ultimate:')
display(consumo_mensual.loc[consumo_mensual['plan'] == 'ultimate', 'total_mensual'].describe())

plt.figure(figsize=(15,5))
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'surf']['total_mensual'], bins=60, alpha=0.6, label='Surf')
plt.hist(consumo_mensual[consumo_mensual['plan'] == 'ultimate']['total_mensual'], bins=60, alpha=0.6, label='Ultimate')
plt.title('Comparación de cargos mensuales entre usuarios con distintos planes')
plt.xlabel('USD')
plt.ylabel('Frecuencia')
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='plan', y='total_mensual', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='Plan', ylabel='USD', title='Distribución cargos mensuales por plan')

plt.show()

usd_total_ciudad = consumo_mensual.groupby(by='plan')['total_mensual'].sum()

usd_total_ciudad.plot(kind = 'bar', title = 'Cargos totales por plan', ylabel= 'USD', color= ['#9b59b6', '#3498db'])

"""El análisis de los cargos mensuales revela diferencias importantes en la forma en que cada plan genera ingresos. El plan ultimate muestra ingresos estables: el 75% de los usuarios paga exactamente la tarifa base y casi ninguno supera los límites incluidos, por lo que los recargos son prácticamente inexistentes. Esto hace que los ingresos del plan ultimate sean predecibles y constantes, con una variabilidad mínima.

En contraste, los usuarios del plan surf presentan un comportamiento de pago mucho más variable. Aunque la tarifa base es considerablemente menor, una proporción significativa de clientes supera los límites incluidos de minutos, mensajes o datos, lo que provoca un aumento notable en los recargos. Como resultado, los ingresos del plan surf son menos consistentes, pero pueden ser considerablemente mayores en aquellos usuarios que exceden ampliamente los límites del plan.

En conjunto, el plan ultimate genera ingresos más estables y uniformes por usuario, mientras que el plan surf presenta ingresos más variables y dependientes del consumo excedente, con el potencial de generar ganancias adicionales gracias a un grupo de usuarios de alto consumo.

## Prueba las hipótesis estadísticas

Hipótesis nula: Las medias de los ingresos de los dos planes no difieren.

Hipótesis alternativa: las medias de los ingresos entre los dos planes son diferentes.

Para evaluar estas hipótesis utilizaremos una prueba t-student para muestras independientes con un nivel de significancia α = 0.05.
Dado que las desviaciones estándar de las dos muestras difieren considerablemente (aproximadamente 11 USD para ultimate y 55 USD para surf), no es adecuado asumir igualdad de varianzas por lo que estableceré el parámetro equal_val = False
"""

# Prueba las hipótesis

alpha = 0.05
results = st.ttest_ind(consumo_mensual.loc[consumo_mensual['plan'] == 'surf', 'total_mensual'], consumo_mensual.loc[consumo_mensual['plan'] == 'ultimate', 'total_mensual'], equal_var = False)

if (results.pvalue < alpha):# su código: compara los valores p obtenidos con el nivel de significación estadística):
    print("Rechazamos la hipótesis nula")
else:
    print("No podemos rechazar la hipótesis nula")

"""

Hipotésis nula: las medias de la muestra de consumidores que son de NY-NJ y la muestra  de los consumidores que son de otras localiades son iguales.

Hipotésis alternativa: las medias de la muestra de consumidores que son de NY-NJ y de la muestra  de los consumidores que son de otras localiades no son iguales.

Para evaluar estas hipótesis utilizaremos una prueba t-student para muestras independientes con un nivel de significancia α = 0.05.
Dado que las desviaciones estándar son similares (aproximadamente 43 USD para NY-NJ y 47 USD para otras ciudades), estableceré el parámetro equal_val = True."""

ciudades = users.set_index('user_id')['city']
consumo_mensual = consumo_mensual.reset_index()
consumo_mensual['city'] = consumo_mensual['user_id'].map(ciudades)
consumo_mensual = consumo_mensual.set_index(['user_id', 'month'])
consumo_mensual['localidad']=np.where(consumo_mensual['city'].str.contains('NY-NJ'),'NY-NJ', 'other')

print('usuarios de NY-NJ:')
display(consumo_mensual.loc[consumo_mensual['localidad'] == 'NY-NJ', 'total_mensual'].describe())
print('=============================================================================================================')
print('usuarios de otras ciudades:')
display(consumo_mensual.loc[consumo_mensual['localidad'] == 'other', 'total_mensual'].describe())

plt.figure(figsize=(15,5))
plt.hist(consumo_mensual[consumo_mensual['localidad'] == 'other' ]['total_mensual'], bins=60, alpha=0.6, label='other')
plt.hist(consumo_mensual[consumo_mensual['localidad'] == 'NY-NJ' ]['total_mensual'], bins=60, alpha=0.6, label='NY-NJ')

plt.title('Comparación de cargos mensuales entre usuarios con distintas localidades')
plt.xlabel('USD')
plt.ylabel('Frecuencia')
plt.legend()
plt.show()

plt.figure(figsize=(8,5))
caja = sns.boxplot(data=consumo_mensual, x='localidad', y='total_mensual', palette= ['#9b59b6', '#3498db'])

caja.set(xlabel='localidad', ylabel='USD', title='Distribución cargos mensuales por localidad')

plt.show()

usd_total_ciudad = consumo_mensual.groupby(by='localidad')['total_mensual'].sum()

usd_total_ciudad.plot(kind = 'bar', title = 'Cargos totales por localidad', ylabel= 'USD', color= ['#9b59b6', '#3498db'])

alpha = 0.05
results = st.ttest_ind(consumo_mensual.loc[consumo_mensual['localidad'] == 'NY-NJ', 'total_mensual'], consumo_mensual.loc[consumo_mensual['localidad'] == 'other', 'total_mensual'], equal_var = True)



if (results.pvalue < alpha):# su código: compara los valores p obtenidos con el nivel de significación estadística):
    print("Rechazamos la hipótesis nula")
else:
    print("No podemos rechazar la hipótesis nula")

"""## Conclusión general

Se analizaron las distribuciones de consumo (minutos, mensajes y datos) y se observó que los grupos comparados presentaban varianzas considerablemente distintas. Por esta razón, en las pruebas de hipótesis entre planes se utilizó la prueba t-student con el parámetro equal_var=False, ya que no se cumplía el supuesto de igualdad de varianzas.
En cambio, para evaluar las diferencias en los ingresos entre localidades, las muestras mostraron desviaciones estándar muy similares, por lo que resultó adecuado aplicar la prueba t-student con equal_var=True.

En todas las pruebas se empleó un nivel de significancia de α = 0.05, criterio utilizado para decidir si las diferencias observadas eran estadísticamente significativas.

El análisis confirmó que el consumo típico de minutos, mensajes y datos es prácticamente igual entre los planes Surf y Ultimate, de modo que las diferencias en ingresos no se explican por patrones de uso, sino por los límites y tarifas que definen cada plan.

El plan Surf se caracteriza por generar ingresos altamente variables, debido a que un porcentaje considerable de usuarios supera los límites incluidos y paga recargos.
Por el contrario, el plan Ultimate ofrece ingresos estables y previsibles, ya que casi ningún usuario excede sus amplios límites de consumo.

También se encontraron diferencias significativas en los ingresos por localidad: los usuarios del resto de ciudades generan, en promedio, mayores ingresos que los de NY-NJ, en parte debido a una mayor incidencia de recargos.

En conjunto, el análisis sugiere lo siguiente:

1- Ultimate maximiza el ingreso por usuario típico, gracias a su tarifa fija de 70 USD.

2- Surf maximiza ingresos a través de usuarios de alto consumo, aunque con una variabilidad mucho mayor.

3 - La localidad influye en los ingresos, siendo “otras ciudades” estadísticamente más rentables que NY-NJ.

4 - El plan surf es el que más ganancias genera.


"""